// <auto-generated />
namespace SShou.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201703192219 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201703192219));
        
        string IMigrationMetadata.Id
        {
            get { return "201703191419253_201703192219"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
