// <auto-generated />
namespace SShou.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20170407eve : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20170407eve));
        
        string IMigrationMetadata.Id
        {
            get { return "201704071441145_20170407eve"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
